name = "InformationPropagationAnalysis"
uuid = "a5102360-ae28-4698-95dd-b3596d53d633"
authors = ["T. Ohiani"]
version = "0.2.1"

[deps]
DataStructures = "864edb3b-99cc-5e75-8d2d-829cb0a9cfe8"
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
ProbabilityBoundsAnalysis = "cd73f0b2-6f06-11ea-242f-83a09de6a7cf"

[compat]
DataStructures = "0.18, 0.19"
DelimitedFiles = "1"
JSON = "0.21, 1"
ProbabilityBoundsAnalysis = "0.2"
julia = "1.12"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
